name: Reusable Deploy
on: 
  workflow_call:
    inputs:
      artifact-name:
        description: Tha name of the deployable artifact files
        required: false
        default: dist
        type: string
    outputs:
      result: 
        description: the result of the deployment outcome
        value: ${{ jobs.deploy.outputs.outcome}}
    # secrets:
    #   some-secret:
    #     required: 
    

jobs:
  deploy:
    outputs:
      outcome: ${{ steps.set-result.outputs.job-result }}
    runs-on: ubuntu-latest
    steps:
      # - name: Get Code
      #   uses: actions/download-artifact@v4
      #   with: 
      #     name: ${{ inputs.artifact-name }}
      - name: List files
        run: ls
      - name: Output information
        run: echo "deploy and upload"
      - name: Set result output
        id: set-result
        run: echo "job-result=Success" >> $GITHUB_OUTPUT